name: Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: sudo systemctl start mysql.service
      - run: ./.travis/install-wp-tests.sh wordpress_test root '' localhost latest
      - run: composer global require "phpunit/phpunit=5.7.*"
      - run: phpunit
      - run: phpunit
        env:
          WP_MULTISITE: 1
