name: Build and Test CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      fail-fast: true
      matrix:
        php:
          - "7.3"
          - "7.4"
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer packages
        uses: actions/cache@v2.1.4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}
            ${{ runner.os }}-php-

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Archive the source
        run: touch plugin-${{ matrix.php }}.tgz && tar czf plugin-${{ matrix.php }}.tgz --exclude=./wordpress/ --exclude=./node_modules/ --exclude=.git/ --exclude="*.tgz" ./

      - name: Upload the source
        uses: actions/upload-artifact@v2
        with:
          name: plugin-${{ matrix.php }}.tgz
          path: plugin-${{ matrix.php }}.tgz
          retention-days: 1

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: true
      matrix:
        php:
          - "7.3"
          - "7.4"
        wpmu:
          - "0"
          - "1"
    steps:
      - name: Start MySQL
        run: sudo systemctl start mysql.service

      - name: Download the source code
        uses: actions/download-artifact@v2
        with:
          name: plugin-${{ matrix.php }}.tgz

      - name: Extract the source code
        run: tar xzf plugin-${{ matrix.php }}.tgz && rm -f plugin-${{ matrix.php }}.tgz

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install WP Test Suite
        run: ./.github/install-wp-tests.sh wordpress_test root root localhost latest

      - name: Run tests
        run: vendor/bin/phpunit
      
      - name: Run tests in multi-site mode
        run: phpunit
        env:
          WP_MULTISITE: ${{ matrix.wpmu }}
